# Generated by Django 5.0.3 on 2024-04-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField()),
                ('data_consulta', models.DateField()),
                ('relato_paciente', models.CharField(max_length=1000)),
                ('laudo', models.CharField(max_length=1000)),
                ('medicacao', models.CharField(max_length=250)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atendente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
    ]
