# Generated by Django 5.0.4 on 2024-04-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_remove_consulta_atendente_remove_consulta_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(help_text='Informe a unidade Federativa', max_length=2, verbose_name='Unidade Federativa')),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('especialidade', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(auto_now_add=True)),
                ('data_consulta', models.DateField()),
                ('relato_paciente', models.TextField()),
                ('laudo', models.TextField()),
                ('medicacao', models.CharField(max_length=100)),
                ('data_modificacao', models.DateField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.atendente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
                ('sintomas', models.ManyToManyField(to='app.sintomas')),
            ],
        ),
    ]
