# Generated by Django 5.0.4 on 2024-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome_completo',
            field=models.CharField(help_text='Informe o nome completo do atendente', max_length=100, verbose_name='Nome do atendente'),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='laudo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='medicacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='relato_paciente',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='app.sintomas'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome_completo',
            field=models.CharField(help_text='Informe o nome completo do medico', max_length=100, verbose_name='Nome do medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(help_text='Informe o nome completo do paciente', max_length=100, verbose_name='Nome do paciente'),
        ),
    ]
