# Generated by Django 5.0.4 on 2024-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_atendente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='data_modificacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_modificacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_modificacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='uf',
            field=models.CharField(help_text='Informe a unidade Federativa', max_length=2, verbose_name='Unidade Federativa'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modificacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
    ]
