# Generated by Django 5.0.4 on 2024-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_atendente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
