# Generated by Django 5.0.7 on 2024-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_atendente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
