# Generated by Django 5.0.7 on 2024-08-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_senha_atendente_password_atendente_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendente',
            old_name='password',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='user_permissions',
        ),
    ]
